### ISSUE TITLE
[BUG]: may have to do with this mod although not sure

### ISSUE THREAD

**Issue by WickedSchnitzel** [AreYSerious/betterruins#22]
### Mod Version

0.1.0

### Game Version

1.18.1

### Platform

Windows

### SP/MP

Multiplayer

### How to reproduce

Its in the console all the time.

### Logs

```[Worldgen] An error was thrown in pass TerrainFeatures when generating chunk column X=1827,Z=2162 in world 'CoBTest' with seed 982821
Exception System.DivideByZeroException: Attempted to divide by zero.
   at Vintagestory.API.MathTools.LCGRandom.NextInt(Int32 max) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Math\LCGRandom.cs:line 149
   at Vintagestory.ServerMods.WorldGenStructure.TryGenerateRuinAtSurface(IBlockAccessor blockAccessor, IWorldAccessor worldForCollectibleResolve, BlockPos pos) in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\WorldGen\Standard\ChunkGen\6.GenStructures\WorldGenStructure.cs:line 438
   at Vintagestory.ServerMods.WorldGenStructure.TryGenerate(IBlockAccessor blockAccessor, IWorldAccessor worldForCollectibleResolve, BlockPos startPos, Int32 climateUpLeft, Int32 climateUpRight, Int32 climateBotLeft, Int32 climateBotRight) in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\WorldGen\Standard\ChunkGen\6.GenStructures\WorldGenStructure.cs:line 225
   at Vintagestory.ServerMods.GenStructures.DoGenStructures(IMapRegion region, Int32 chunkX, Int32 chunkZ, Boolean postPass, ITreeAttribute chunkGenParams) in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\WorldGen\Standard\ChunkGen\6.GenStructures\GenStructures.cs:line 228
   at Vintagestory.ServerMods.GenStructures.OnChunkColumnGen(IChunkColumnGenerateRequest request) in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\WorldGen\Standard\ChunkGen\6.GenStructures\GenStructures.cs:line 159
   at Vintagestory.Server.ServerSystemSupplyChunks.runGenerators(ChunkColumnLoadRequest chunkRequest, Int32 forPass) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\Systems\World\LoadThread\SupplyChunks.cs:line 1474```

**Comment by AreYSerious** [comment]
Yeah can be ignored... It gets spammed sometimes while worldgen but the structures are OK. I guess it can be bcs of the size
